# Generated by Django 4.2.4 on 2023-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lastname', models.TextField()),
                ('birth_id', models.TextField()),
                ('cell_phone_no', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('street', models.TextField()),
                ('street_no', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('zip_code', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
