# Generated by Django 4.2.4 on 2023-08-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='photo',
            field=models.ImageField(default=None, upload_to='pojisteni/CSS/'),
        ),
    ]
