# Generated by Django 4.2.4 on 2023-08-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0002_policyholder_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyholder',
            name='photo',
            field=models.ImageField(upload_to='pojisteni/CSS/'),
        ),
    ]
