# Generated by Django 4.2.4 on 2023-08-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0004_insurancemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancemodel',
            name='paid_by',
            field=models.CharField(choices=[('POK', 'Pojistník'), ('POJ', 'Pojištěnec')], default='POJ', max_length=20),
        ),
        migrations.AlterField(
            model_name='insurancemodel',
            name='insurance_type',
            field=models.CharField(choices=[('PM', 'Pojištění majetku'), ('ZP', 'Životní pojištění'), ('CP', 'Cestovní pojištění'), ('PR', 'Povinné ručení'), ('HP', 'Havarijní pojištění'), ('UP', 'Úrazové pojištění'), ('JP', 'Jiné pojištění')], default='PM', max_length=30),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='birth_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='cell_phone_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='street',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='street_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
