# Generated by Django 4.2.4 on 2023-08-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0005_insurancemodel_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancemodel',
            name='policyholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni.policyholder', to_field='birth_id'),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='birth_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
