# Generated by Django 4.2.4 on 2023-08-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0006_alter_insurancemodel_policyholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancemodel',
            name='policyholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni.policyholder'),
        ),
    ]
