# Generated by Django 4.2.4 on 2023-08-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0010_remove_insurancemodel_insurance_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancemodel',
            name='insurance_object',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
