# Generated by Django 4.2.4 on 2023-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0011_insurancemodel_insurance_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancemodel',
            name='target_amount',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
