# Generated by Django 4.2.4 on 2023-08-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0014_alter_insurancemodel_target_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyholder',
            name='photo',
            field=models.ImageField(upload_to='pojisteni/static/pojisteni/JPG/'),
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contract_no', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('desc', models.TextField()),
                ('attach1', models.FileField(blank=True, null=True, upload_to='pojisteni/static/pojisteni/FILES/')),
                ('attach2', models.FileField(blank=True, null=True, upload_to='pojisteni/static/pojisteni/FILES/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni.policyholder')),
            ],
        ),
    ]
